[window]
padding.x = 8
padding.y = 8
decorations = "full"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono" }
offset.y = 5

[shell]
program = "wsl"
args = ["-d", "Ubuntu", "--cd ~"]

[keyboard]
bindings = [
    { key = "Key6", mods = "Control", chars = "\u001e" },
    { key = "Space", mods = "Control", chars = "\u0000" },
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
]

